---
- name: Create pica directory
  file: path={{config_dir}} state=directory mode=0755

- name: Install pica config file
  copy: src={{config_file}} dest={{config_dir}}/{{config_file}} mode=0644
  notify: load_config
